#!/usr/bin/python
# -*- coding: utf-8 -*-

from gengee import common
from gengee.portage import *
from github import Github

keywords = ["bump", "revbump", "verbump", "drop", "eapi", "use", "license", "security", "static", "cross", "fix"]
config = common.getConfig()

try:
    g = Github(config["github_token"])
    r = g.get_repo("gentoo/gentoo")
except Exception as e:
    print(str(e))
    exit()

pulls = []
repo_path = getRepoPath()

for pull in r.get_pulls('open'):
    PR = pull.number
    print(str(PR) + " :: " + pull.title)

    p = {
        "comment_count": pull.comments,
        "commit_count": pull.commits,
        "ebuilds": set(),
        "eclasses": set(),
        "files": [],
        "file_count": pull.changed_files,
        "keywords": [],
        "labels": [],
        "maintainers": [],
        "manifest": False,
        "mergeable": pull.mergeable,
        "number": str(PR),
        "packages": set(),
        "title": pull.title,
        "updated": pull.updated_at.strftime("%Y-%m-%d"),
        "user": pull.user.login
    }
    for l in pull.labels:
        p["labels"].append(l.name)

    # keywords, match from selected list
    for match_kw in keywords:
        if match_kw in p["title"].lower():
            p["keywords"].append(match_kw)

    # only get files when
    if p["file_count"] < config["file_scan_max"]:
        for c in pull.get_files():
            split_fn = c.filename.split("/")
            if split_fn[0] == "eclass":
                p["eclasses"].add(split_fn[1])
            elif "-" not in split_fn[0]:
                # don't do anything with license/profile
                pass
            else:
                p["packages"].add(split_fn[0] + "/" + split_fn[1])
            p["files"].append(c.filename)
            if c.filename[-7:] == ".ebuild":
                p["ebuilds"].add(split_fn[2][:-7])
            if c.filename[-9:] == "/Manifest":
                p["manifest"] = True

    for package in p["packages"]:
        p["maintainers"] = getMaintainers(package,repo_path)

    # set to list because not json serializable
    p["ebuilds"] = list(p["ebuilds"])
    p["eclasses"] = list(p["eclasses"])
    p["packages"] = list(p["packages"])

    pulls.append(p)

# and write
common.writeDB(pulls)
